#!/bin/bash

# set default independent variables
ROOT="${PWD}"
DISTRO_DIR="${ROOT}/distributions"
PROJECT_DIR="${ROOT}/projects"

# determines DISTRO, if not forced by user
export DISTRO="${DISTRO:-LibreELEC}"

# determines PROJECT, if not forced by user
export PROJECT="${PROJECT:-Generic}"

# default to Generic device if building Generic project without device set
if [ "${PROJECT}" = "Generic" -a -z "${DEVICE}" ]; then
  export DEVICE="Generic"
fi

# determines TARGET_ARCH, if not forced by user
export ARCH="${ARCH:-x86_64}"
TARGET_ARCH="${ARCH}"
