#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2017-present Team LibreELEC (https://libreelec.tv)

import os
import sys

print("{} is deprecated and will be remove next release. Please update your scripts to use build_matrix\n".format(sys.argv[0]))

exec(open("{}/{}".format(os.path.dirname(__file__), "build_matrix")).read())
