name: update-binary-addons
on:
  workflow_dispatch:
    inputs:
      input_addon-version:
        description: "Add-on version to update"
        default: 12.0
        required: true
        type: string
jobs:
  update_addon_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: libreelec-12.0
      - name: update-binary
        env: 
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
        run: |
          echo "-------1234------"
          export GH_API_KEY="$GH_API_KEY"
          echo "${#GH_API_KEY}"
          echo "-------1234------"
          echo "Updating Add-on version ${{ github.event.inputs.input_addon-version }}"
          cd "tools/mkpkg/"
          ./update_binary-addons Omega -x
          echo "----------------------------------------"
          echo "----------------------------------------"
          git status
          echo "----------------------------------------"
          echo "----------------------------------------"
