jobs:
  update_addon_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: libreelec-12
      - name: update-binary
        run: |
          echo "Updating Add-on version ${{ github.event.inputs.input_addon-version }}"
          cd "tools/mkpkg/"
          ./update_binary-addons Omega -x
          echo "----------------------------------------"
          echo "----------------------------------------"
          git status
          echo "----------------------------------------"
          echo "----------------------------------------"
